//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from MyGrammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class MyGrammarLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, NUMBER=11, IDENTIFIER=12, WS=13;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "NUMBER", "IDENTIFIER", "WS"
	};


	public MyGrammarLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public MyGrammarLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'-'", "'+'", "'^'", "'*'", "'/'", "'max'", "'('", "','", "')'", 
		"'min'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, "NUMBER", 
		"IDENTIFIER", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MyGrammar.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static MyGrammarLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,13,75,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,1,0,1,0,1,1,1,1,
		1,2,1,2,1,3,1,3,1,4,1,4,1,5,1,5,1,5,1,5,1,6,1,6,1,7,1,7,1,8,1,8,1,9,1,
		9,1,9,1,9,1,10,4,10,53,8,10,11,10,12,10,54,1,11,4,11,58,8,11,11,11,12,
		11,59,1,11,1,11,5,11,64,8,11,10,11,12,11,67,9,11,1,12,4,12,70,8,12,11,
		12,12,12,71,1,12,1,12,0,0,13,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,
		10,21,11,23,12,25,13,1,0,4,1,0,48,57,2,0,65,90,97,122,1,0,49,57,3,0,9,
		10,13,13,32,32,78,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,
		1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,
		0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,1,27,1,0,0,0,3,29,1,0,0,0,5,31,
		1,0,0,0,7,33,1,0,0,0,9,35,1,0,0,0,11,37,1,0,0,0,13,41,1,0,0,0,15,43,1,
		0,0,0,17,45,1,0,0,0,19,47,1,0,0,0,21,52,1,0,0,0,23,57,1,0,0,0,25,69,1,
		0,0,0,27,28,5,45,0,0,28,2,1,0,0,0,29,30,5,43,0,0,30,4,1,0,0,0,31,32,5,
		94,0,0,32,6,1,0,0,0,33,34,5,42,0,0,34,8,1,0,0,0,35,36,5,47,0,0,36,10,1,
		0,0,0,37,38,5,109,0,0,38,39,5,97,0,0,39,40,5,120,0,0,40,12,1,0,0,0,41,
		42,5,40,0,0,42,14,1,0,0,0,43,44,5,44,0,0,44,16,1,0,0,0,45,46,5,41,0,0,
		46,18,1,0,0,0,47,48,5,109,0,0,48,49,5,105,0,0,49,50,5,110,0,0,50,20,1,
		0,0,0,51,53,7,0,0,0,52,51,1,0,0,0,53,54,1,0,0,0,54,52,1,0,0,0,54,55,1,
		0,0,0,55,22,1,0,0,0,56,58,7,1,0,0,57,56,1,0,0,0,58,59,1,0,0,0,59,57,1,
		0,0,0,59,60,1,0,0,0,60,61,1,0,0,0,61,65,7,2,0,0,62,64,7,0,0,0,63,62,1,
		0,0,0,64,67,1,0,0,0,65,63,1,0,0,0,65,66,1,0,0,0,66,24,1,0,0,0,67,65,1,
		0,0,0,68,70,7,3,0,0,69,68,1,0,0,0,70,71,1,0,0,0,71,69,1,0,0,0,71,72,1,
		0,0,0,72,73,1,0,0,0,73,74,6,12,0,0,74,26,1,0,0,0,5,0,54,59,65,71,1,6,0,
		0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
